baseURL = 'https://bell-favorite-recipes.onrender.com/'
languageCode = 'en-us'
title = 'Bell Favorite Recipes'

[params]
  description = "Favorite recipes from friends, family, and around the web"
  author = "Billy Bell"
  mainSections = ["recipes"]
  dateFormat = "January 2, 2006"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "All Recipes"
    url = "/recipes/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "What's In My Fridge?"
    url = "/whats-cooking/"
    weight = 4
  [[menu.main]]
    name = "My Recipe Book"
    url = "/my-recipe-book/"
    weight = 5
  [[menu.main]]
    name = "Submit a Recipe"
    url = "/submit/"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[taxonomies]
  category = "categories"
  tag = "tags"
  subcategory = "subcategories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
